### ISSUE TITLE
Missing "r" property 

### ISSUE THREAD

**Issue by diervo** [microsoft/vscode-custom-data#46]
The following code 
```css
.vertex {
        filter: drop-shadow(rgba(207, 171, 255, 0.9) 0px 0px 20px);
        fill: #b082ee;
        r: 20;
        stroke: 5;
    }
```

`Unknown property: 'r'lit-plugin(no-invalid-css)`
